# configuration parameters
paths:
  data_raw: ./data/raw
  data_processed: ./data/processed
  images: ./images
  report: ./report
  addons: ./addons
  logs: ./logs

# network/retries for all scrapers
scraper:
  timeout_s: 30
  retries: 3
  backoff_factor: 1.0
  user_agent: "FinDataCleaner/0.1 (+https://example.com; contact: admin@example.com)"

api_keys:
  eia: dcqfqnNdUo3BZqyLGkonSosWUGUwS2g07E0WJL1X